accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views


urlpatterns = patterns('',
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^login/submit/$', views.login_handler, name='submit'),
                       url(r'^logout/$', views.logout_handler, name='logout'),
                       url(r'^create/$', views.create_account_handler, name='create'),
                       url(r'^profile/$', views.profile_view, name='profile'),
                       url(r'^new/$', views.new_user_view, name='new_user'),
                       url(r'^new/submit/$', views.new_user_handler, name='submit_new_user'),
                       url(r'^new/support/', views.new_support_user_view, name='new_support'),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'untitled.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^about/$', views.about_view, name='about'),
                       url(r'^home/$', views.homepage_view, name='home'),
                       url(r'^$', views.index_view, name='index'),
)

journal/urls.py
from django.conf.urls import patterns, url

from journal import views


urlpatterns = patterns('',
                       url(r'^$', views.index_view, name='index'),
                       url(r'^submit/', views.entry_submit_handler, name='submit'),
                       url(r'^delete/', views.entry_delete_handler, name='delete'),
)

moodgraph/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import landing

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'untitled.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('landing.urls', namespace="landing")),
    url(r'^beta/', include('home.urls', namespace='home')),
    url(r'^beta/graphs/', include('graphs.urls', namespace='graphs')),
    url(r'^beta/support/', include('support.urls', namespace='support')),
    url(r'^beta/user/', include('user.urls', namespace='user')),
    url(r'^beta/accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^beta/journal/', include('journal.urls', namespace='journal')),
    url(r'^beta/admin/', include('admin_area.urls', namespace='admin_area')),
)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect

# Create your views here.
@login_required
def homepage_view(request):
    user = request.user
    return render(request, 'home/home.html', {'user': user,})


def index_view(request):
    return render(request, 'home/index.html')


def about_view(request):
    return render(request, 'home/about.html')

home/templates/home/about.html
{% extends 'main/base.html' %}
{% load staticfiles %}


{% block title %}About{% endblock %}
{% block links %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home:index' %}">Home <i class="fa fa-home"></i></a></li>
        <li class="active"><a href="{% url 'home:about' %}">About <i class="fa fa-star"></i></a></li>
    </ul>
{% endblock %}

{% block image %}{% static 'main/images/sweden5.jpg' %}{% endblock %}

{% block content %}
    <div class="jumbotron">
        <img src="{% static 'main/images/uphoros_logo_blue.png' %}"/>

        <p>Optimizing relationships between individuals and mental health professionals to conquer mental
            illness.</p>
    </div>
    <br/>

    <div class="container-fluid col-md-8">
        <div class="card">
            <div class="container-fluid">
                <h1 class="page-header orange-header">The <img class="about_logo" src="{% static 'main/images/uphoros_logo_blue.png' %}"/> vision</h1>

                <p>
                    In the summer of 2014, <b>Üphoros</b> (originally MoodGraph) began as an idea to reinvent the mood tracking application on web
                    and mobile, but ultimately that idea evolved into something much more useful. <b>Üphoros</b> now
                    represents the utilization of technology in an effort to better the lives of those afflicted with
                    mental and emotional disorders. By encouraging individuals to analyze their mood on a daily basis,
                    <b>Üphoros</b> increases overall self-awareness; however, the real strength of our application resides in
                    its ability to connect individuals with their support system in an efficient, instantaneous, and
                    secure way.
                </p>

                <h1 class="page-header orange-header">Why <img class="about_logo" src="{% static 'main/images/uphoros_logo_blue.png' %}"/> matters</h1>

                <p>
                    Mental health is one of the biggest societal and medical challenges the world is facing and will
                    continue to face in the foreseeable future. One in ten Americans will be depressed at some point in
                    their lives, and this number is on the raise. Bipolar disorder affects a large number of Americans
                    as well, with approximately 5.7 million currently diagnosed. In 2013 alone there were approximately
                    41,000 suicides, many of them attributable at least in part to a mental or emotional disorder of
                    some kind. At <b>Üphoros</b> we find these numbers unacceptable, and our primary goal is to reduce the
                    number of deaths and hospital visits related to untreated and poorly treated mood disorders.
                    <br/><br/>
                    <b>Üphoros</b> works to solve the fundamental problem faced in treatment of mood disorders: the problem
                    of communicating emotions effectively. This problem is not easily solved, but the current system
                    of going days, weeks, or months at a time between therapy sessions without any communication of
                    emotional state simply doesn't work. Emotional memory is fairly short-term, and perceptions of
                    memories are affected by mood. Unfortunately, this results in patients misremembering information
                    that could potentially be critical to effective treatment of their mental illness. Also, many times
                    that an individual should reach out for help, they feel too depressed to do so. A passive way to ask
                    for help could resolve this. Can a web application entirely fix these problems? Probably not, but it
                    can certainly provide a foundation to be built upon by more proactive, focused treatment methods.
                </p>

                <h1 class="page-header orange-header">How <img class="about_logo" src="{% static 'main/images/uphoros_logo_blue.png' %}"/> works</h1>
                <p>
                    <b>Üphoros</b> increases efficiency in the treatment of mood disorders by providing a full-featured
                    technology platform for mental health. This platform provides services for tracking mental health
                    data, visualizing that data, and subsequently sharing that information constantly and
                    instantaneously with family members, friends, therapists, or anyone else involved in an individual's
                    treatment. In addition to the mood tracking and visualization services, <b>Üphoros</b> also automatically
                    notifies an individual's support network when he or she feels unsafe, allowing intervention
                    before the individual can harm themselves or others. However, <b>Üphoros</b> is always changing, and if
                    you have an idea that could help you or someone you know in their struggle with mental illness, feel
                    free to contact me by email at acp2142@gmail.com
                </p>
            </div>
        </div>
    </div>
    <div class="container-fluid col-md-4">
        <div class="card">
            <div class="container-fluid">
                <h1 class="page-header orange-header">Team</h1>

                <div>
                    <div class="card-user">

                        <div class="image">


                        </div>

                        <div class="content">

                            <div class="author">

                                <a href="#">

                                    <img class="avatar" src="{% static 'main/assets/img/faces/austin.jpg' %}"
                                         alt="..."/>


                                    <h4 class="title">Austin Prete<br/>

                                        <small>Founder</small>
                                        <br/>
                                        <small>Programmer</small>
                                        <br/>
                                        <small>Designer</small>

                                    </h4>

                                </a>

                            </div>

                            <p class="description text-center">

                                <i class="fa fa-map-marker text-muted"></i> Salt Lake City, UT <br>

                                <i class="fa fa-envelope-o text-muted"></i> acp2142@gmail.com <br>

                                <i class="fa fa-clock-o text-muted"></i> Since June 2014

                            </p>

                        </div>

                        <hr>

                        <div class="text-center">

                            <button href="#" class="btn btn-social btn-simple"><i
                                    class="fa fa-facebook-square"></i>
                            </button>

                            <button href="#" class="btn btn-social btn-simple"><i
                                    class="fa fa-twitter"></i>
                            </button>

                            <button href="#" class="btn btn-social btn-simple"><i
                                    class="fa fa-google-plus-square"></i>
                            </button>


                        </div>

                    </div>
                    <!-- end card -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/home.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block title %}Home{% endblock %}
{% block home_link %}active{% endblock %}

{% block image %}{% static 'main/images/sweden1.jpg' %}{% endblock %}

{% block content %}
    <div class="card col-md-6">
        <div class="container-fluid">
            {% block welcome %}
                <h1 class="page-header orange-header">Welcome
                    {% if user.first_name != "" %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}!</h1>
            {% endblock %}

            <div class="container-fluid card">
                <h2 class="text-center page-header" style="color:#9c9c9c; font-weight:200">
                    News
                </h2>
                <ul>
                    <li>Public access to the beta will begin on February 1, 2015.</li>
                    <li>First official release is scheduled for May 1, 2015.</li>
                </ul>
                <br/>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/index.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block image %}{% static 'main/images/sweden1.jpg' %}{% endblock %}

{% block links %}
    <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'home:index' %}">Home <i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'home:about' %}">About <i class="fa fa-star"></i></a></li>
    </ul>   {% endblock %}

{% block content %}
    <div class="jumbotron">
        <img src="{% static 'main/images/uphoros_logo_blue.png' %}"/>

        <p>Optimizing relationships between individuals and mental health professionals to conquer mental
            illness.</p>
    </div>

    <div class="col-md-6 container-fluid card">
        <h1 class="page-header orange-header">Login</h1>

        <form action="{% url 'accounts:submit' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="Username" name="username" class="form-control"/>
            <br/>
            <input type="password" placeholder="Password" name="password" class="form-control"/>
            <br/>
            <input type="submit" value="Login" class="btn btn-info" class="form-control"/>
        </form>
        <br/>

        <p><a href="{% url 'accounts:login' %}"> Click here to create a new account.<a/></p>

        <h2 class="text-center page-header" style="color:#9c9c9c; font-weight:200">
            News
        </h2>
        <ul>
            <li>Public access to the beta will begin on April 1, 2015.</li>
            <li>First official release is scheduled for June 1, 2015.</li>
        </ul>
        <br/>
    </div>
{% endblock %}