accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views


urlpatterns = patterns('',
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^login/submit/$', views.login_handler, name='submit'),
                       url(r'^logout/$', views.logout_handler, name='logout'),
                       url(r'^create/$', views.create_account_handler, name='create'),
                       url(r'^profile/$', views.profile_view, name='profile'),
                       url(r'^new/$', views.new_user_view, name='new_user'),
                       url(r'^new/submit/$', views.new_user_handler, name='submit_new_user'),
                       url(r'^new/support/', views.new_support_user_view, name='new_support'),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'untitled.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^about/$', views.about_view, name='about'),
                       url(r'^home/$', views.homepage_view, name='home'),
                       url(r'^$', views.index_view, name='index'),
)

moodgraph/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import landing

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'untitled.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('landing.urls', namespace="landing")),
    url(r'^beta/', include('home.urls', namespace='home')),
    url(r'^beta/graphs/', include('graphs.urls', namespace='graphs')),
    url(r'^beta/support/', include('support.urls', namespace='support')),
    url(r'^beta/user/', include('user.urls', namespace='user')),
    url(r'^beta/accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^beta/journal/', include('journal.urls', namespace='journal')),
    url(r'^beta/admin/', include('admin_area.urls', namespace='admin_area')),
)

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class PersonalUser(models.Model):
    user = models.OneToOneField(User)
    gender_choices = [
        ('MA', 'Male'),
        ('FE', 'Female'),
    ]
    gender = models.CharField(max_length=10, choices=gender_choices)
    birthdate = models.DateField(null=True)
    age = models.IntegerField(null=True)


class SupportUser(models.Model):
    user = models.OneToOneField(PersonalUser)
    code = models.IntegerField()
    phone_number = models.CharField(max_length=20)

accounts/views.py
from time import strptime, mktime
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect


# Create your views here.
from accounts.models import PersonalUser


def login_view(request):
    return render(request, 'accounts/login.html')

def login_handler(request):
    post = request.POST
    username = post['username']
    password = post['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            if user.first_name != "" and hasattr(user, 'personaluser'):
                return redirect(reverse('home:home'))
            else:
                return redirect(reverse('accounts:new_user'))
        else:
            message = "This account is inactive."
    else:
        message = "Username or password does not match our records."
    return render(request, 'accounts/login.html', {'message': message,})


def create_account_handler(request):
    post = request.POST
    username = post['username']
    email = post['email']
    password = post['password']
    try:
        User.objects.create_user(username, email, password)
    except:
        message = "Username is already taken."
        return render(request, 'accounts/login.html', {'message': message,})
    user = authenticate(username=username, password=password)
    login(request, user)
    if 'support' in post:
        return redirect(reverse('accounts:new_support'))
    return redirect(reverse('accounts:new_user'))


@login_required
def logout_handler(request):
    logout(request)
    return redirect(reverse('home:index'))


@login_required
def profile_view(request):
    user = request.user
    if user.first_name != "":
        name = user.first_name
    else:
        name = user.username
    return render(request, 'accounts/profile.html', {'user': user, 'name': name, })


@login_required
def new_user_view(request):
    return render(request, 'accounts/newuser.html')


@login_required
def new_user_handler(request):
    post = request.POST
    user = request.user
    user.first_name = post['first_name']
    user.last_name = post['last_name']
    user.save()
    personal_user = PersonalUser(user=user)
    personal_user.save()
    personal_user.gender = post['gender']
    birthdate = strptime(post['birthdate'], "%m/%d/%Y")
    date = datetime.datetime.fromtimestamp(mktime(birthdate))
    personal_user.birthdate = date
    personal_user.age = (datetime.datetime.now() - date).days / 365
    personal_user.save()
    return redirect(reverse('accounts:profile'))


@login_required
def new_support_user_view(request):
    return render(request, 'accounts/newsupport.html')

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block title %}Login{% endblock %}

{% block links %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home:index' %}">Home <i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'home:about' %}">About <i class="fa fa-star"></i></a></li>
    </ul>
{% endblock %}

{% block image %}{% static 'main/images/sweden2.jpg' %}{% endblock %}

{% block content %}
    <div class="card container-fluid col-md-12">
        {% if message %}
            <br/>
            <div class="alert alert-danger">
                <div class="container">
                    <b>{{ message }}</b>
                </div>
            </div>
        {% endif %}
        <h1 class="page-header orange-header">Login</h1>

        <form action="{% url 'accounts:submit' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="Username" name="username" class="form-control"/>
            <br/>
            <input type="password" placeholder="Password" name="password" class="form-control"/>
            <br/>
            <input type="submit" value="Login" class="btn btn-info" class="form-control"/>
        </form>
        <h1 class="page-header orange-header">Create a new account</h1>

        <form action="{% url 'accounts:create' %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="Username" class="form-control" name="username"/>
            <br/>
            <input type="email" placeholder="Email" class="form-control" name="email"/>
            <br/>
            <input type="password" placeholder="Password" class="form-control" name="password"/>
            <br/>
            <span>Are you creating an account primarily to support one or more other individuals?</span><input type="checkbox"
                                                                                                        class="form-control" name="support" />
            <br/>
            <input type="submit" value="Create Account" class="form-control btn btn-info"/>
        </form>
        <br/>
    </div>
{% endblock %}

accounts/templates/accounts/newsupport.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block title %}New Support Account{% endblock %}

{% block image %}{% static 'main/images/sweden2.jpg' %}{% endblock %}

{% block content %}
    <div class="card">
        <div class="container-fluid">
            <h1 class="page-header orange-header">New Support Account <br/>
            <small>Please fill out this additional information in order to create a support account</small>
            </h1>
            <form class="form-group">
                {% csrf_token %}
                <input type="tel" pattern='[\(]\d{3}[\)][\-]\d{3}[\-]\d{4}' class="form-control" placeholder="Phone number: (XXX)-XXX-XXXX"/>
                <br/>
                <input type="submit" class="form-control btn-warning" value="Submit"/>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/newuser.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card">
    <div class="container-fluid">
        <!-- Main jumbotron -->
        <h1 class="page-header" style="color:orange; font-weight:200">New Profile
            <small><br/>Please fill out the following information</small>
        </h1>
        <form type="form" action="{% url 'accounts:submit_new_user' %}" method="post">
            {% csrf_token %}
            <div class="form-group col-md-6">
                <input type="text" class="form-control" placeholder="First Name" name="first_name"/>
                <br/>
                <input type="text" class="form-control" placeholder="Last Name" name="last_name"/>
                <br/>
                <select name="gender" class="selectpicker" data-style="form-control" data-menu-style="">

                    <option disabled selected>Gender</option>

                    <option value="Male">Male</option>

                    <option value="Female">Female</option>

                </select>
                <br/>
                <br/>
                <input class="datepicker form-control" type="text" placeholder="Birthdate - MM/DD/YYYY"
                       name="birthdate"/>
                <br/>
                <button type="submit" class="btn btn-warning">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block title %}{{ user.first_name }}{% endblock %}

{% block profile_link %}active{% endblock %}

{% block image %}{% static 'main/images/sweden6.jpg' %}{% endblock %}

{% block content %}
    <div class="card col-md-4">
        <div class="container-fluid">
            <h1 class="page-header orange-header">Profile <i class="fa fa-user"></i></h1>

            <div class="card">
                <div class="container-fluid">
                    <h4>Name: <span style="font-weight: lighter">{{ user.first_name }} {{ user.last_name }}</span></h4>
                    <h4>Email Address: <span style="font-weight: lighter">{{ user.email }}</span></h4>
                    <h4>Gender: <span style="font-weight: lighter">{{ user.personaluser.gender }}</span></h4>
                    <h4>Age: <span style="font-weight: lighter">{{ user.personaluser.age }}</span></h4>
                    <h4>Birthdate: <span style="font-weight: lighter">{{ user.personaluser.birthdate }}</span></h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}