accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views


urlpatterns = patterns('',
                       url(r'^login/$', views.login_view, name='login'),
                       url(r'^login/submit/$', views.login_handler, name='submit'),
                       url(r'^logout/$', views.logout_handler, name='logout'),
                       url(r'^create/$', views.create_account_handler, name='create'),
                       url(r'^profile/$', views.profile_view, name='profile'),
                       url(r'^new/$', views.new_user_view, name='new_user'),
                       url(r'^new/submit/$', views.new_user_handler, name='submit_new_user'),
                       url(r'^new/support/', views.new_support_user_view, name='new_support'),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'untitled.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^about/$', views.about_view, name='about'),
                       url(r'^home/$', views.homepage_view, name='home'),
                       url(r'^$', views.index_view, name='index'),
)

moodgraph/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import landing

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'untitled.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('landing.urls', namespace="landing")),
    url(r'^beta/', include('home.urls', namespace='home')),
    url(r'^beta/graphs/', include('graphs.urls', namespace='graphs')),
    url(r'^beta/support/', include('support.urls', namespace='support')),
    url(r'^beta/user/', include('user.urls', namespace='user')),
    url(r'^beta/accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^beta/journal/', include('journal.urls', namespace='journal')),
    url(r'^beta/admin/', include('admin_area.urls', namespace='admin_area')),
)

user/urls.py
from django.conf.urls import patterns, url

from user import views


urlpatterns = patterns('',
                       url(r'^$', views.profile_view, name="profile"),
)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

main/templates/main/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" type="image/png" href="{% static 'main/assets/img/favicon.ico' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>Üphoros - {% block title %}{% endblock %}</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width"/>

    <link href="{% static 'main/bootstrap3/css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'main/assets/css/gsdk.css' %}" rel="stylesheet"/>

    <link href="{% static 'main/assets/css/demo.css' %}" rel="stylesheet"/>
    <link href="{% static 'main/assets/css/style.css' %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'main/assets/css/pe-icon-7-stroke.css' %}" rel="stylesheet"/>

</head>
<body>

<!-- Navbar will come here -->
<nav class="navbar navbar-ct-azure">
    <div class="container-fluid">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">

                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'home:home' %}"><img class="uphoros_logo" src="{% static 'main/images/uphoros_logo.png' %}"</a>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% block links %}
                    <li class="{% block home_link %}{% endblock %}"><a href="{% url 'home:home' %}">Home <i
                            class="fa fa-home"></i></a></li>
                    <li class="{% block journal_link %}{% endblock %}"><a
                            href="{% url 'journal:index' %}">Journal <i class="fa fa-book"></i></a></li>
                    <li class="{% block graphs_link %}{% endblock %}"><a href="{% url 'graphs:index' %}">Graphs <i
                            class="fa fa-line-chart"></i></a>
                    </li>
                    <li class="{% block support_link %}{% endblock %}"><a href="{% url 'support:index' %}">Support
                        Network <i class="fa fa-users"></i></a></li>
                {% endblock %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="{% block profile_link %}{% endblock %}"><a href="{% url 'accounts:profile' %}">
                        {% if user.first_name != "" %}{{ user.first_name }}{% else %}
                            {{ user.username }}{% endif %} <i class="fa fa-user"></i></a></li>
                    <li>
                        <button class="navbar-btn btn btn-sm btn-default"><a href="{% url 'accounts:logout' %}"
                                                                             style="color:white">Logout</a>
                        </button>
                    </li>
                {% else %}
                    <li>
                        <button class="navbar-btn btn btn-sm btn-default"><a href='{% url 'accounts:login' %}'
                                                                             style="color:white">Login</a>
                        </button>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- end navbar -->

<div class="main" style="background-image: url({% block image %}{% endblock %}); ">
</div>
<br/>

<div class="wrapper" style="background-color: transparent;">
    <div class="container">
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<div class="main_footer"></div>

</body>

<script src="{% static 'main/assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
<script src="{% static 'main/assets/js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

<script src="{% static 'main/bootstrap3/js/bootstrap.js' %}" type="text/javascript"></script>

<!--  Plugins -->
<script src="{% static 'main/assets/js/gsdk-checkbox.js' %}"></script>
<script src="{% static 'main/assets/js/gsdk-morphing.js' %}"></script>
<script src="{% static 'main/assets/js/gsdk-radio.js' %}"></script>
<script src="{% static 'main/assets/js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static 'main/assets/js/bootstrap-select.js' %}"></script>
<script src="{% static 'main/assets/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'main/assets/js/chartist.min.js' %}"></script>
<script src="{% static 'main/assets/js/jquery.tagsinput.js' %}"></script>
<script src="{% static 'main/assets/js/Chart.min.js' %}"></script>
<script src="{% static 'main/assets/js/get-shit-done.js' %}"></script>
<script src="{% static 'main/assets/js/jquery.flexisel.js' %}"></script>
{% block script %}
{% endblock %}
</html>