admin_area/urls.py
from django.conf.urls import patterns, url
from admin_area import views

urlpatterns = patterns('',
                       url(r'^$', views.index_view, name="index"),
                       url(r'^users/$', views.users_view, name="users"),
                       url(r'^subscribers/$', views.subscribers_view, name="subscribers"),
                       url(r'^subscribers/message/', views.message_subscribers_handler, name='message_subscribers'),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'untitled.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^about/$', views.about_view, name='about'),
                       url(r'^home/$', views.homepage_view, name='home'),
                       url(r'^$', views.index_view, name='index'),
)

moodgraph/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import landing

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'untitled.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('landing.urls', namespace="landing")),
    url(r'^beta/', include('home.urls', namespace='home')),
    url(r'^beta/graphs/', include('graphs.urls', namespace='graphs')),
    url(r'^beta/support/', include('support.urls', namespace='support')),
    url(r'^beta/user/', include('user.urls', namespace='user')),
    url(r'^beta/accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^beta/journal/', include('journal.urls', namespace='journal')),
    url(r'^beta/admin/', include('admin_area.urls', namespace='admin_area')),
)

user/urls.py
from django.conf.urls import patterns, url

from user import views


urlpatterns = patterns('',
                       url(r'^$', views.profile_view, name="profile"),
)

admin_area/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

admin_area/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core import mail
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect

# Create your views here.
from landing.models import Subscriber


@user_passes_test(lambda u: u.is_superuser)
def index_view(request):
    return render(request, 'admin_area/index.html')


@user_passes_test(lambda u: u.is_superuser)
def users_view(request):
    users = User.objects.all()
    return render(request, 'admin_area/users.html', {'users': users,})


@user_passes_test(lambda u: u.is_superuser)
def subscribers_view(request):
    subscribers = Subscriber.objects.all()
    return render(request, 'admin_area/subscribers.html', {'subscribers': subscribers,})


@user_passes_test(lambda u: u.is_superuser)
def message_subscribers_handler(request):
    post = request.POST
    user = request.user
    subscribers = Subscriber.objects.all()
    if subscribers:
        connection = mail.get_connection()
        for subscriber in subscribers:
            send_mail(post['subject'], post['message'], 'admin@moodgraph.net', [subscriber.email,], connection=connection)
    return redirect(reverse('admin_area:index'))

user/views.py
from django.shortcuts import render

# Create your views here.
def profile_view(request):
    return render(request, 'user/profile.html', {'logged_in': True, 'user': request.user})

admin_area/templates/admin_area/index.html
{% extends 'main/base.html' %}

{% block title %}Admin{% endblock %}


{% block links %}
    <li class="active"><a href="{% url 'admin_area:index' %}">Home</a></li>
    <li><a href="{% url 'admin_area:users' %}">Users</a></li>
    <li><a href="{% url 'admin_area:subscribers' %}">Subscribers</a></li>
{% endblock %}

{% block content %}
    <div class="card container-fluid">

        <div class="container-fluid">
            <h2 class="page-header">Message all subscribers</h2>
            <form role="form" action="{% url 'admin_area:message_subscribers' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="subject" placeholder="Subject"/>
                </div>
                <div class="form-group">
                    <textarea type="text" class="form-control" name="message"
                              placeholder="Message all subscribers..."></textarea>
                </div>
                <button class="btn btn-primary" type="submit">Send</button>
            </form>
            <br/>
        </div>
    </div>
{% endblock %}

admin_area/templates/admin_area/subscribers.html
{% extends 'main/base.html' %}


{% block links %}
    <li><a href="{% url 'admin_area:index' %}">Home</a></li>
    <li><a href="{% url 'admin_area:users' %}">Users</a></li>
    <li class="active"><a href="{% url 'admin_area:subscribers' %}">Subscribers</a></li>
{% endblock %}


{% block content %}
    <div class="container-fluid card">
        <div class="table-responsive">

            <table class="table">

                <thead>

                <tr>

                    <th class="text-center">#</th>

                    <th>Email</th>

                    <th>Actions</th>


                </tr>

                </thead>

                <tbody>
                {% block body %}
                {% for subscriber in subscribers %}

                <tr>
                    <td class="text-center">{{ forloop.counter }}
                    </th>
                    <td>{{ subscriber.email }}</td>
                    <td class="td-actions">
                        <form action="/admin/subscribers/message" method="get" style="display: inline">
                            <button type="submit" rel="tooltip" title="Message User" value="{{ subscriber.email }}"
                                    name="user_email"
                                    class="btn btn-success btn-simple btn-xs">

                                <i class="fa fa-edit"></i>

                            </button>
                        </form>

                        <form action="/admin/subscribers/delete" method="post" style="display: inline;">
                            <button type="submit" rel="tooltip" title="Remove"
                                    value="{{ subscriber.id }}" name="delete_button"
                                    class="btn btn-danger btn-simple btn-xs">

                                <i class="fa fa-times"></i>

                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                {% endblock %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

admin_area/templates/admin_area/users.html
{% extends 'main/base.html' %}


{% block links %}
    <li><a href="{% url 'admin_area:index' %}">Home</a></li>
    <li class="active"><a href="{% url 'admin_area:users' %}">Users</a></li>
    <li><a href="{% url 'admin_area:subscribers' %}">Subscribers</a></li>
{% endblock %}

{% block content %}
    <div class="card container-fluid">
        <div class="table-responsive">

            <table class="table">

                <thead>

                <tr>

                    <th class="text-center">#</th>

                    <th>Name</th>
                    <th>Email</th>
                    <th>Actions</th>


                </tr>

                </thead>

                <tbody>
                {% block body %}
                    {% for user in users %}

                        <tr>
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td>{{ user.last_name }}, {{ user.first_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="td-actions">
                                <form action="/admin/users/message" method="get" style="display: inline">
                                    <button type="submit" rel="tooltip" title="Message User" value="{{ user.email }}"
                                            name="user_email"
                                            class="btn btn-success btn-simple btn-xs">

                                        <i class="fa fa-edit"></i>

                                    </button>
                                </form>

                                <form action="/admin/users/delete" method="post" style="display: inline;">
                                    <button type="submit" rel="tooltip" title="Remove"
                                            value="{{ user.id }}" name="delete_button"
                                            class="btn btn-danger btn-simple btn-xs">

                                        <i class="fa fa-times"></i>

                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                {% endblock %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}